import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: {
		default: 'Thoughts Agency',
		template: '%s | Thoughts Agency'
	},
	description: 'Generated by shk.'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className}`}>
				<div className="flex flex-col justify-between m-auto container h-screen">
					<Navbar />
					{children}
					<Footer />
				</div>
			</body>
		</html>
	);
}
